version: '3.9'

services:
  flask_app:

    container_name: flask_app
    tty: true
    stdin_open: true
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app/app.py
    command:
      - flask
      - run
      - --host=0.0.0.0
    restart: always
    expose:
      - 5000
    ports:
      - "5000:5000"
